# build an image starting with the Python 3.7 image
FROM python:3.8

# set the working directory to /MovieRecApp-MovieService
WORKDIR /MovieRecApp-MovieService

# install dependencies
COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# adding metadata to the image to describe that the container is listening on port 5000
EXPOSE 5000
# set the default command for the container to python3 application.py
CMD["python3", "application.py"]